name: demo
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2
      - run: yarn install
      - name: Verify
        run: yarn workspaces run verify
  Deploy-Dev:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - run: echo "second job"
  Deploy-Staging:
    runs-on: ubuntu-latest
    needs: Deploy-Dev
    if: ${{github.ref == 'refs/heads/main'}}
    steps:
      - run: echo "third job"