name: demo
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        run: actions/checkout@v2
      - run: yarn install
      - run: yarn run test
  Second-Job:
    runs-on: ubuntu-latest
    needs: First-Job
    steps:
      - run: echo "second job"
  Third-Job:
    runs-on: ubuntu-latest
    needs: Second-Job
    if: ${{github.ref == 'refs/heads/main'}}
    steps:
      - run: echo "third job"